"""initial

Revision ID: 8967aa432ec4
Revises: 
Create Date: 2025-11-24 22:00:02.890251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8967aa432ec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_kategori', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('role', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resep',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_resep', sa.String(length=250), nullable=False),
    sa.Column('gambar', sa.String(length=500), nullable=False),
    sa.Column('waktu_masak', sa.Integer(), nullable=False),
    sa.Column('kategori_id', sa.BigInteger(), nullable=False),
    sa.Column('deskripsi_singkat', sa.Text(), nullable=False),
    sa.Column('alat_dan_bahan', sa.Text(), nullable=False),
    sa.Column('langkah_langkah', sa.Text(), nullable=False),
    sa.Column('dibuat_oleh', sa.BigInteger(), nullable=False),
    sa.Column('is_top_pick', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['user.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sorotan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_sorotan', sa.String(length=250), nullable=False),
    sa.Column('gambar_sorotan', sa.String(length=500), nullable=False),
    sa.Column('waktu_sorotan', sa.Integer(), nullable=False),
    sa.Column('kategori_id', sa.BigInteger(), nullable=False),
    sa.Column('deskripsi_sorotan', sa.Text(), nullable=False),
    sa.Column('alat_sorotan', sa.Text(), nullable=False),
    sa.Column('langkah_sorotan', sa.Text(), nullable=False),
    sa.Column('penulis', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.ForeignKeyConstraint(['penulis'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('resep_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resep_id'], ['resep.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorit')
    op.drop_table('sorotan')
    op.drop_table('resep')
    op.drop_table('user')
    op.drop_table('kategori')
    # ### end Alembic commands ###
